package com.ken.carrental.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ken.carrental.common.BaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.Date;

/**
 * generated by schedule task
 * each time slot stands for 30 minutes
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
@TableName("tb_car_time_slot")
public class CarTimeSlot extends BaseEntity {

    private Integer carId;

    private Integer carModelId;

    private Integer status;

    private Integer orderId;

    // start of the time slot
    private Date timeSlot;
}
